var1 = "김성민"  #문자열(String)
var2 = 27       #정수(Integer)
var3 = 100.1    #실수(Float)
var4 = True     #논리(Boolean)
print(var1, id(var1), type(var1))
print(var2, id(var2), type(var2))
print(var3, id(var3), type(var3))
print(var4, id(var4), type(var4))